networks:
  - name: vpc-public
    description: VPC
    bridge: virbr101
    cidr: 10.10.0.0/24
    netmask: 255.255.255.0
    ip_address: 10.10.0.1
    dhcp:
      start: 10.10.0.100
      end:   10.10.0.254
    forward: nat
    autostart: true
    routes: []   # optional extra routes

  - name: private-subnet-a
    description: Private subnet (a.k.a availability zone "A")
    bridge: virbr102
    cidr: 10.10.1.0/24
    netmask: 255.255.255.0
    ip_address: 10.10.1.1
    dhcp:
      start: 10.10.1.100
      end:   10.10.1.254
    forward: nat
    autostart: true
    routes: []   # optional extra routes

  - name: private-subnet-b
    description: Private subnet (a.k.a availability zone "B")
    bridge: virbr103
    cidr: 10.10.2.0/24
    netmask: 255.255.255.0
    ip_address: 10.10.2.1
    dhcp:
      start: 10.10.2.100
      end:   10.10.2.254
    forward: nat
    autostart: true
    routes: []   # optional extra routes

vm: pass   